### ISSUE TITLE
No module named 'detector'

### ISSUE THREAD

**Issue by xiaofeng-c** [gmt710/AlphaPose_yolovx#1]
**Thanks for your work!When i run with the command of sh ./scripts/inference.sh ${CONFIG} ${CHECKPOINT} ${VIDEO_NAME},a error occur as follow:**
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 13, in <module>
    from detector.apis import get_detector
ModuleNotFoundError: No module named 'detector'
**Do you know how to solve this question?**

**Comment by gmt710** [comment]
Hello, May you try this command :
```
python setup.py build develop --user

python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x-dcn.yaml --checkpoint pretrained_models/fast_dcn_res50_256x192.pth --indir examples/demo/ --vis --showbox --save_img --pose_track --sp --vis_fast --detector yolov5
```
