### ISSUE TITLE
when i change 256x192_res50_lr1e-3_2x-dcn.yaml to 256x192_res50_lr1e-3_1x.yaml,get error

### ISSUE THREAD

**Issue by EllisHui** [gmt710/AlphaPose_yolovx#4]
my command is :
python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir pic_in_dir --outdir pic_out_dir --showbox --save_img --pose_track --sp --vis_fast --detector yolov5
my virtuenv is success like yours
the error is like below:
![2021-08-18_153813](https://user-images.githubusercontent.com/42332058/129858113-30e901d5-a6c1-43e4-a8d8-4576181eebae.png)

**Comment by gmt710** [comment]
The model was not downloaded successfully ?
