### ISSUE TITLE
error in deformable_im2col: invalid device function 段错误 (核心已转储)

### ISSUE THREAD

**Issue by HanjieJi** [gmt710/AlphaPose_yolovx#5]
Hello, thanks for your nice work!
my command is `python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x-dcn.yaml --checkpoint pretrained_models/fast_dcn_res50_256x192.pth --indir test_img  --outdir examples/demo/ --showbox --save_img --pose_track --vis_fast --detector yolov5`
but something is wrong said: `error in deformable_im2col: invalid device function  段错误 (核心已转储)`
Could someone do me a favor?

**Comment by HanjieJi** [comment]
And also I want to know that could this work can deal with video, like change command `--indir test_img` to `--video test_video`

**Comment by gmt710** [comment]
Maybe it has something to do with the version of cuda.

> Hello, thanks for your nice work!
> my command is `python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x-dcn.yaml --checkpoint pretrained_models/fast_dcn_res50_256x192.pth --indir test_img --outdir examples/demo/ --showbox --save_img --pose_track --vis_fast --detector yolov5`
> but something is wrong said: `error in deformable_im2col: invalid device function 段错误 (核心已转储)`
> Could someone do me a favor?

**Comment by HanjieJi** [comment]
Yes！I changed cuda version to 10.1 and solved it！Thanks！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月20日(周五) 晚上11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gmt710/AlphaPose_yolovx] error in deformable_im2col: invalid device function 段错误 (核心已转储) (#5)




 
Maybe it has something to do with the version of cuda.
  
Hello, thanks for your nice work!
 my command is python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x-dcn.yaml --checkpoint pretrained_models/fast_dcn_res50_256x192.pth --indir test_img --outdir examples/demo/ --showbox --save_img --pose_track --vis_fast --detector yolov5
 but something is wrong said: error in deformable_im2col: invalid device function 段错误 (核心已转储)
 Could someone do me a favor?
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gmt710** [comment]
It should work, maybe you need to look at the code.

> And also I want to know that could this work can deal with video, like change command `--indir test_img` to `--video test_video`

**Comment by gmt710** [comment]
@HanjieJi okay, I'll close this issue.
