### ISSUE TITLE
error: ‘AT_CHECK’ was not declared in this scope

### ISSUE THREAD

**Issue by jyh3690** [gmt710/AlphaPose_yolovx#7]
hi,when i  take "python setup.py build develop --user",there is an error like that:

detector/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")

i dont konw how to do ?can you help me?

**Comment by gmt710** [comment]
https://github.com/MVIG-SJTU/AlphaPose/issues/701

**Comment by Klawens** [comment]
把所有的AT_CHECK换成TORCH_CHECK

**Comment by gmt710** [comment]
Good! I'll close this issue, be free to reopen it.
